name: CI

on:
  pull_request:
    branches: [$default-branch]
  push:
    branches: [$default-branch, next]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          # Comment out next line when testing with `act`
          cache: 'npm'
      - run: npm install
      - run: npx prettier . --check
      # - run: npm run lint
      - run: npm test
